version: "3.8"

services:

  postgres:
    image: postgres:16.2
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - posgres-data:/var/lib/postgresql/data
    networks:
      - my-fitness-pal-to-grafana-network

networks:
  my-fitness-pal-to-grafana-network:
    driver: bridge

volumes:
  postgres-data:
